export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAIL = "GET_ARTICLES_FAIL";

export const GET_ARTICLE_DETAILS = "GET_ARTICLE_DETAILS";
export const GET_ARTICLE_DETAILS_SUCCESS = "GET_ARTICLE_DETAILS_SUCCESS";
export const GET_ARTICLE_DETAILS_FAIL = "GET_ARTICLE_DETAILS_FAIL";
